### ISSUE TITLE
Composer + Pakagist

### ISSUE THREAD

**Issue by nazbav** [slmatthew/vk-coin-php#2]
Было бы хорошо, если ваша библиотека могла бы подключается через композитор...

Доп материал:
Сервис для добавления библиотек в композитор - https://packagist.org

Сделал мелкие правки:
https://github.com/nazbav/vk-coin-php
1. Не было return-ов в некоторых комментах
2. не знаю зачем, но заменил "{$parm}" на sprintf('%u',$parm); -- дополнительно проверяет нужного ли типа данные будут вставлены.

**Comment by slmatthew** [comment]
Окей, спасибо! Добавлю Ваш код и залью в composer
