### ISSUE TITLE
getTransactions

### ISSUE THREAD

**Issue by pixenth** [slmatthew/vk-coin-php#5]
Делаю, значит, запрос такого плана:
`$vcoin_tx = $vkcoin->getTransactions();`
В итоге приходит ответ, для удобства преобразовал его в JSON-формат:
`{"status":true,"response":[]}`
Транзакции на аккаунте совершались, но response, как видно, пустой. С чем может быть связано?

**Comment by slmatthew** [comment]
По умолчанию [параметр tx](https://vk.com/@hs-marchant-api?anchor=poluchenie-spiska-tranzaktsy) равен единице, а это значит, что возвращаются 1000 последних транзакций **со ссылок на оплату**. Чтобы получить последние 100 транзакций на текущий аккаунт, следует использовать этот код:
```php
$vcoin_tx = $vkcoin->getTransactions(2);
```
